# -----------------------------
# PostgreSQL configuration file
# -----------------------------

listen_addresses = '*'
max_connections = 200			# (change requires restart)
shared_buffers = 128MB			# min 128kB
maintenance_work_mem = 1024MB		# min 1MB
dynamic_shared_memory_type = posix	# the default is usually the first option
max_parallel_maintenance_workers = 4	# limited by max_parallel_workers
wal_level = minimal			# minimal, replica, or logical
synchronous_commit = off		# synchronization level;
max_wal_size = 1GB
min_wal_size = 80MB
max_wal_senders = 0		# max number of walsender processes
log_timezone = 'Etc/UTC'
datestyle = 'iso, mdy'
timezone = 'Etc/UTC'
lc_messages = 'en_US.utf8'		# locale for system error message
lc_monetary = 'en_US.utf8'		# locale for monetary formatting
lc_numeric = 'en_US.utf8'		# locale for number formatting
lc_time = 'en_US.utf8'			# locale for time formatting
default_text_search_config = 'pg_catalog.english'
pg_stat_statements.track = all
pg_stat_statements.max = 10000
pg_stat_statements.save = on
shared_preload_libraries = 'pg_ivm, pg_curl, pg_stat_statements,auto_explain'

